-- CafeOps Intelligence Project — V1 database schema
-- Target: existing Supabase PostgreSQL project (ap-northeast-1)
-- Synthetic/demo baseline. Review before applying to any production database.
-- Safe to run on a fresh project; uses CREATE TABLE IF NOT EXISTS.
begin;

create extension if not exists pgcrypto;

-- Tenant and access model
create table if not exists public.organizations (
  organization_id text primary key,
  organization_name text not null,
  currency char(3) not null default 'GBP',
  timezone text not null default 'Europe/London',
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  location_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_name text not null,
  address text,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  unique (organization_id, location_id)
);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  role text not null check (role in ('owner','admin','manager','staff','viewer')),
  default_location_id text references public.locations(location_id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_location_access (
  user_id uuid not null references public.user_profiles(user_id) on delete cascade,
  location_id text not null references public.locations(location_id) on delete cascade,
  primary key (user_id, location_id)
);

-- Staff and catalog
create table if not exists public.employees (
  employee_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  first_name text not null,
  last_name text not null,
  role text not null,
  hourly_rate numeric(10,2) not null check (hourly_rate >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  menu_item_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  sku text not null,
  menu_item_name text not null,
  category text not null,
  size text not null default 'Standard',
  list_price numeric(12,2) not null check (list_price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, sku)
);

create table if not exists public.ingredients (
  ingredient_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  ingredient_name text not null,
  base_unit text not null,
  purchase_pack_size numeric(14,4) not null check (purchase_pack_size > 0),
  purchase_pack_unit text not null,
  latest_pack_cost numeric(12,4) not null check (latest_pack_cost >= 0),
  unit_cost numeric(14,6) not null check (unit_cost >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.recipes (
  recipe_line_id bigint generated by default as identity primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  recipe_id text not null,
  menu_item_id text not null references public.menu_items(menu_item_id) on delete restrict,
  recipe_version integer not null check (recipe_version > 0),
  ingredient_id text not null references public.ingredients(ingredient_id) on delete restrict,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null,
  effective_from date not null,
  effective_to date,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from),
  unique (organization_id, recipe_id, ingredient_id)
);

-- Vendor and purchasing
create table if not exists public.vendors (
  vendor_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  vendor_name text not null,
  payment_terms text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vendor_items (
  vendor_item_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  vendor_id text not null references public.vendors(vendor_id) on delete restrict,
  ingredient_id text not null references public.ingredients(ingredient_id) on delete restrict,
  vendor_sku text,
  pack_size numeric(14,4) not null check (pack_size > 0),
  pack_unit text not null,
  current_pack_price numeric(12,4) not null check (current_pack_price >= 0),
  currency char(3) not null default 'GBP',
  valid_from date not null,
  unique (organization_id, vendor_id, ingredient_id, valid_from)
);

create table if not exists public.purchase_orders (
  purchase_order_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  vendor_id text not null references public.vendors(vendor_id) on delete restrict,
  order_date date not null,
  expected_date date,
  status text not null check (status in ('draft','submitted','partially_received','received','cancelled')),
  currency char(3) not null default 'GBP',
  created_at timestamptz not null default now()
);

create table if not exists public.purchase_order_lines (
  purchase_order_line_id text primary key,
  purchase_order_id text not null references public.purchase_orders(purchase_order_id) on delete restrict,
  ingredient_id text not null references public.ingredients(ingredient_id) on delete restrict,
  quantity_ordered numeric(14,4) not null check (quantity_ordered > 0),
  quantity_received numeric(14,4) not null default 0 check (quantity_received >= 0 and quantity_received <= quantity_ordered),
  unit text not null,
  unit_price numeric(12,4) not null check (unit_price >= 0),
  line_total numeric(14,2) not null check (line_total >= 0)
);

create table if not exists public.invoices (
  invoice_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  vendor_id text not null references public.vendors(vendor_id) on delete restrict,
  purchase_order_id text references public.purchase_orders(purchase_order_id) on delete restrict,
  invoice_number text not null,
  invoice_date date not null,
  due_date date,
  status text not null check (status in ('draft','open','paid','overdue','void')),
  currency char(3) not null default 'GBP',
  total_amount numeric(14,2) not null check (total_amount >= 0),
  unique (organization_id, vendor_id, invoice_number)
);

create table if not exists public.invoice_lines (
  invoice_line_id text primary key,
  invoice_id text not null references public.invoices(invoice_id) on delete cascade,
  ingredient_id text references public.ingredients(ingredient_id) on delete restrict,
  description text not null,
  quantity numeric(14,4) not null check (quantity >= 0),
  unit text not null,
  unit_price numeric(12,4) not null check (unit_price >= 0),
  line_total numeric(14,2) not null check (line_total >= 0)
);

-- Sales and future Square integration
create table if not exists public.sales_transactions (
  transaction_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  source_system text not null,
  source_transaction_id text not null,
  created_at timestamptz not null,
  currency char(3) not null default 'GBP',
  status text not null check (status in ('pending','completed','cancelled','refunded')),
  payment_status text not null check (payment_status in ('unpaid','paid','partially_refunded','refunded')),
  imported_at timestamptz not null default now(),
  unique (organization_id, source_system, source_transaction_id)
);

create table if not exists public.sales_lines (
  sales_line_id text primary key,
  transaction_id text not null references public.sales_transactions(transaction_id) on delete cascade,
  menu_item_id text not null references public.menu_items(menu_item_id) on delete restrict,
  quantity numeric(12,4) not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  line_total numeric(14,2) not null check (line_total >= 0),
  tax_amount numeric(12,2) not null default 0 check (tax_amount >= 0)
);

create table if not exists public.square_sync_state (
  sync_state_id bigint generated by default as identity primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  square_location_id text,
  last_successful_cursor text,
  last_successful_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (organization_id, location_id)
);

-- Inventory ledger (base-unit movements; balances should be derived or periodically reconciled)
create table if not exists public.inventory_balances (
  inventory_balance_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  ingredient_id text not null references public.ingredients(ingredient_id) on delete restrict,
  as_of_date date not null,
  opening_quantity numeric(14,4) not null,
  unit text not null,
  reorder_point numeric(14,4) not null default 0 check (reorder_point >= 0),
  target_quantity numeric(14,4) not null default 0 check (target_quantity >= 0),
  unique (organization_id, location_id, ingredient_id, as_of_date)
);

create table if not exists public.inventory_transactions (
  inventory_transaction_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  ingredient_id text not null references public.ingredients(ingredient_id) on delete restrict,
  movement_date timestamptz not null,
  movement_type text not null check (movement_type in ('opening_balance','purchase_receipt','theoretical_consumption','waste','count_adjustment','transfer_in','transfer_out')),
  quantity_change numeric(14,4) not null,
  unit text not null,
  reference_type text,
  reference_id text,
  notes text,
  created_at timestamptz not null default now()
);

-- Labor and scheduling
create table if not exists public.shifts (
  shift_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  shift_date date not null,
  start_time time not null,
  end_time time not null,
  planned boolean not null default true,
  check (end_time > start_time)
);

create table if not exists public.labor_records (
  labor_record_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text not null references public.locations(location_id) on delete restrict,
  employee_id text not null references public.employees(employee_id) on delete restrict,
  shift_id text references public.shifts(shift_id) on delete set null,
  work_date date not null,
  hours_worked numeric(8,2) not null check (hours_worked >= 0),
  hourly_rate numeric(10,2) not null check (hourly_rate >= 0),
  labor_cost numeric(12,2) not null check (labor_cost >= 0),
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

-- Traceability, import staging and audit
create table if not exists public.import_jobs (
  import_job_id uuid primary key default gen_random_uuid(),
  organization_id text references public.organizations(organization_id) on delete restrict,
  source_system text not null check (source_system in ('xlsx','square','manual','other')),
  source_file_name text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'pending' check (status in ('pending','running','success','partial','failed')),
  rows_read integer not null default 0 check (rows_read >= 0),
  rows_inserted integer not null default 0 check (rows_inserted >= 0),
  rows_rejected integer not null default 0 check (rows_rejected >= 0),
  error_summary text,
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.sync_jobs (
  sync_job_id text primary key,
  organization_id text not null references public.organizations(organization_id) on delete restrict,
  location_id text references public.locations(location_id) on delete restrict,
  source_system text not null,
  job_type text not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  status text not null check (status in ('running','success','partial','failed')),
  records_read integer not null default 0,
  records_written integer not null default 0,
  error_message text
);

create table if not exists public.metric_definitions (
  metric_key text primary key,
  metric_name text not null,
  proposed_formula text not null,
  unit text not null,
  approval_status text not null default 'proposed' check (approval_status in ('proposed','approved','retired')),
  definition_version integer not null default 1,
  updated_at timestamptz not null default now()
);

-- Query indexes
create index if not exists idx_sales_txn_org_loc_created on public.sales_transactions(organization_id, location_id, created_at);
create index if not exists idx_sales_lines_transaction on public.sales_lines(transaction_id);
create index if not exists idx_inventory_txn_loc_ing_date on public.inventory_transactions(organization_id, location_id, ingredient_id, movement_date);
create index if not exists idx_labor_org_loc_date on public.labor_records(organization_id, location_id, work_date);
create index if not exists idx_po_org_loc_date on public.purchase_orders(organization_id, location_id, order_date);
create index if not exists idx_invoice_org_loc_date on public.invoices(organization_id, location_id, invoice_date);
create index if not exists idx_recipe_effective on public.recipes(menu_item_id, effective_from, effective_to);

-- Enable RLS on business tables. Policies below allow authenticated users only
-- when a matching profile and location membership exist. Owners/admins can see
-- all locations in their organization; other roles require explicit location access.
do $$
declare t text;
begin
  foreach t in array array[
    'organizations','locations','user_profiles','user_location_access','employees',
    'menu_items','ingredients','recipes','vendors','vendor_items','purchase_orders',
    'purchase_order_lines','invoices','invoice_lines','sales_transactions','sales_lines',
    'square_sync_state','inventory_balances','inventory_transactions','shifts',
    'labor_records','import_jobs','sync_jobs','metric_definitions'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- Helper functions use the authenticated user's profile.
create or replace function public.current_org_id()
returns text language sql stable security definer set search_path = public
as $$ select organization_id from public.user_profiles where user_id = auth.uid() $$;

create or replace function public.can_access_location(p_location_id text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.user_profiles p
    join public.locations l on l.organization_id = p.organization_id
    where p.user_id = auth.uid()
      and l.location_id = p_location_id
      and (
        p.role in ('owner','admin')
        or exists (select 1 from public.user_location_access a
                   where a.user_id = p.user_id and a.location_id = p_location_id)
      )
  )
$$;

-- Remove/recreate policies idempotently.
-- Apply organization-only policies only to tables that directly contain organization_id.
do $$
declare t text;
begin
  foreach t in array array[
    'locations','employees','menu_items','ingredients','recipes','vendors','vendor_items'
  ] loop
    execute format('drop policy if exists tenant_select on public.%I', t);
    execute format(
      'create policy tenant_select on public.%I
       for select to authenticated
       using (organization_id = public.current_org_id())',
      t
    );
  end loop;
end $$;

-- Tables with both organization_id and location_id.
do $$
declare t text;
begin
  foreach t in array array[
    'purchase_orders','invoices','sales_transactions',
    'square_sync_state','inventory_balances','inventory_transactions',
    'shifts','labor_records','sync_jobs'
  ] loop
    execute format('drop policy if exists tenant_select on public.%I', t);
    execute format(
      'create policy tenant_select on public.%I
       for select to authenticated
       using (
         organization_id = public.current_org_id()
         and public.can_access_location(location_id)
       )',
      t
    );
  end loop;
end $$;

-- Child tables: derive tenant/location access through their parent.
drop policy if exists tenant_select on public.purchase_order_lines;
create policy tenant_select on public.purchase_order_lines
for select to authenticated
using (
  exists (
    select 1
    from public.purchase_orders po
    where po.purchase_order_id = purchase_order_lines.purchase_order_id
      and po.organization_id = public.current_org_id()
      and public.can_access_location(po.location_id)
  )
);

drop policy if exists tenant_select on public.invoice_lines;
create policy tenant_select on public.invoice_lines
for select to authenticated
using (
  exists (
    select 1
    from public.invoices i
    where i.invoice_id = invoice_lines.invoice_id
      and i.organization_id = public.current_org_id()
      and public.can_access_location(i.location_id)
  )
);

drop policy if exists tenant_select on public.sales_lines;
create policy tenant_select on public.sales_lines
for select to authenticated
using (
  exists (
    select 1
    from public.sales_transactions st
    where st.transaction_id = sales_lines.transaction_id
      and st.organization_id = public.current_org_id()
      and public.can_access_location(st.location_id)
  )
);

-- Writes are intentionally server/service-role only for V1. Never expose service-role key.
-- No authenticated INSERT/UPDATE/DELETE policies are created by this migration.

commit;
